---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - iproute2
          - tcpdump
          - net-tools
          - python3
          - python3-pip
          - curl
        state: present

    - name: Add Webmin repository key
      apt_key:
        url: https://download.webmin.com/jcameron-key.asc
        state: present

    - name: Add Webmin repository
      apt_repository:
        repo: "deb https://download.webmin.com/download/repository sarge contrib"
        state: present
        filename: webmin

    - name: Install Webmin for network management UI
      apt:
        name: webmin
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Configure Netplan for network interfaces
      copy:
        content: |
          network:
            version: 2
            ethernets:
              eth0:
                dhcp4: yes
              eth1:
                addresses:
                  - 192.168.0.{{ 100 + ansible_play_hosts.index(inventory_hostname) }}/24
                routes:
                  - to: 192.168.1.0/24
                    via: 192.168.0.1
        dest: /etc/netplan/01-netcfg.yaml
      notify: Apply netplan configuration

    - name: Start HTTP server on server1
      shell: |
        if ! pgrep -f "python3 -m http.server 8080"; then
          nohup python3 -m http.server 8080 > /dev/null 2>&1 &
        fi
      when: inventory_hostname == "server1"

    - name: Send HTTP request from server2 to server1
      command: curl http://93.183.74.93:8080
      when: inventory_hostname == "server2"
      register: curl_log

    - name: Вывод curl from server2 to server1
      debug:
        var: curl_log.stdout_lines

  handlers:
    - name: Apply netplan configuration
      command: netplan apply